config/routes.rb
Distributor::Application.routes.draw do
  controller :session do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'session/new'
  get 'session/create'
  get 'session/destroy'

  resources :issues

  resources :sprints do
    patch 'close', on: :member
  end

  root 'issues#index'

  namespace :api do
    resources :event, only: [] do
      collection do
        post '/recieve', to: "event#recieve"
      end
    end
  end
end

app/models/client.rb
class Client < ActiveRecord::Base
  has_many :sprint_clients
  has_many :sprints, through: :sprint_clients
  has_many :issues
  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ActiveRecord::Base
  belongs_to :issue
end

app/models/issue.rb
class Issue < ActiveRecord::Base
  has_many :events
  belongs_to :sprint
  belongs_to :client, foreign_key: :redmine_user_id,
                      primary_key: :redmine_id
  validate :issue_hours, on: :update

  def issue_hours
    opened = Sprint.where(state: true).first
    errors.add(:issue_id, I18n.t(:too_many_hours)) if (opened.nil? || opened.estimated_hours_to_sprint +
      estimated_hours > opened.work_hours) && sprint.present?
  end

  def process_in_percents
    ((hours / estimated_hours) * 100).to_i
  end
end

app/models/sprint.rb
class Sprint < ActiveRecord::Base
  has_many :sprint_clients
  has_many :clients, through: :sprint_clients
  has_many :issues
  has_many :events, through: :issues
  validates :name, uniqueness: true, presence: true
  validates :clients, presence: true
  validate :all_sprints_closed, on: :update
  #validate :open_sprint
  #validate :start_sprint
  validates :work_hours, numericality: { greater_than_or_equal_to: :estimated_hours_to_sprint }, on: :update
  accepts_nested_attributes_for :clients

  def open_sprint
    opened = Sprint.where(state: 1).first
    errors.add(:sprint_id, I18n.t(:can_not_be_updated)) if
                opened && (state == 0)
  end

  def start_sprint
    started = Sprint.where(state: 2).first
    errors.add(:sprint_id, I18n.t(:work_sprint_already_exists)) if
                started && (state != 1)
  end

  def all_sprints_closed
    opened = Sprint.where(state: 1).any? || Sprint.where(state: 2).any?
    errors.add(:sprint_id, I18n.t(:this_sprint_already_closed)) unless opened
  end

  def estimated_hours_to_sprint
    issues.sum(:estimated_hours)
  end

  def hours_to_sprint
    issues.sum(:hours)
  end

  def process_in_percents
    ((hours_to_sprint / work_hours) * 100).to_i
  end

  def graph
    shrinking_time = work_hours
    mas = events.group(:hours_date).sum(:hours)
    (start_time..Date.today).each { |date| mas[date] = 0 unless mas.key?(date) }
    mas = Hash[mas.sort]
    mas.update(mas) { |_key, value| shrinking_time -= value }
  end
end

app/models/sprint_client.rb
class SprintClient < ActiveRecord::Base
  belongs_to :client
  belongs_to :sprint
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/api/dataredmine_controller.rb
class Api::DataredmineController < ApiController
  skip_before_filter :verify_authenticity_token, only: [:recieve]
  skip_before_filter :authorize

  def recieve
    if params[:object] == 'time entry'
      @event = Event.find_or_initialize_by(id: params[:time_entry_id])
      @event.assign_attributes(issue_id: params[:issue_id],
                               hours: params[:hours],
                               client_id: params[:redmine_id],
                               hours_date: params[:hours_date])
      return ActiveRecord::RecordNotSaved unless @event.save
    else
      @issue = Issue.find_or_initialize_by(id: params[:issue_id])
      @issue.assign_attributes(estimated_hours: params[:estimated_hours],
                               hours: params[:hours],
                               status: params[:status],
                               subject: params[:issue_subject],
                               redmine_user_id: params[:redmine_id])
      return ActiveRecord::RecordNotSaved unless @issue.save
    end
  end
end

app/controllers/api_controller.rb
class ApiController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :authorize

  protected

  def authorize
    return if User.find_by(id: session[:user_id])
    redirect_to login_url, notice: t('.auth')
  end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_filter :current_sprint, only: :index

  def index
    @issues = Issue.all
    @issue_url = Rails.configuration.issue_url
  end

  # def update
  #   @issue = Issue.where(id: params[:id]).first

  #   respond_to do |format|
  #     format.html # index.html.erb
  #     format.json { render json: @activities }
  #     if @issue
  #       flash[:notice] = t('.issue_can_not_be_updated') unless
  #@issue.update(sprint_id: params[:sprint_id])
  #     else
  #       flash[:notice] = t('.issue_is_not_found')
  #     end
  #   end
  #   redirect_to issues_path
  # end

  def update
    @issue = Issue.where(id: params[:id]).first

    respond_to do |format|
      if @issue.update(sprint_id: params[:sprint_id])
        format.json { render json: @issue }
      else
        format.html { redirect_to issues_path, notice: t('.issue_can_not_be_updated') }
        format.json
      end
      format.html { redirect_to issues_path }
    end
  end

  private

  def current_sprint
    @sprint = Sprint.where(state: 1).first
    return redirect_to sprints_path unless @sprint
  end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_action :authorize

  def create
    user = User.where(name: params[:name]).first
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to issues_url
    else
      redirect_to login_url, alert: t('.incorrect_user_name_or_pass')
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to login_url, notice: t('.session_completed')
  end
end

app/controllers/sprints_controller.rb
class SprintsController < ApplicationController
  skip_before_filter :authorize, only: [:show, :index]
  before_action :set_sprint, only: [:show, :edit, :update, :destroy, :close, :start]
  before_action :all_clients, only: [:new, :edit, :create, :update]
  before_filter :collect_selected_clients, only: [:create, :edit, :update]

  def index
    @sprints = Sprint.all
  end

  def show
    @issue_url = Rails.configuration.issue_url
    @events = @sprint.events
  end

  def new
    @sprint = Sprint.new
  end

  def create
    @sprint = Sprint.new(sprint_params)
    if @sprint.save
      clients_work_hours
      return redirect_to sprints_url
    end
    render :new
  end

  def update
    if @sprint.update(sprint_params)
      clients_work_hours
      return redirect_to @sprint
    end
    render :edit
  end

  def destroy
    return redirect_to sprints_url if @sprint.destroy
  end

  def close
    @sprint.update(state: 0)? flash[:notice] = t(:sprint_was_closed) : flash[:notice] = t(:sprint_cannot_close)
    redirect_to sprints_path
  end

  def start
    if @sprint.update_attributes(state: 2, start_time: Date.today)
      flash[:notice] = t(:sprint_started)
      redirect_to sprint_path(@sprint)
    else
      flash[:notice] = t(:sprint_can_not_start)
      redirect_to issues_path
    end
  end

  private

  def set_sprint
    @sprint = Sprint.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to sprint_url, notice: t('.sprint_not_found')
  end

  def sprint_params
    params.require(:sprint).permit(:name, :state, :work_hours, client_ids: [])
  end

  def collect_selected_clients
    @collect_selected = (@sprint.present? && @sprint.clients.any?) ? @sprint.clients.map(&:id) : []
  end

  def all_clients
    @clients = Client.all
  end

  def clients_work_hours
    @sprint.update_attributes(work_hours: @sprint.clients.count * 40)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @total_clients = Client.count
  end
end

app/helpers/issues_helper.rb
module IssuesHelper
  def progressbar_percent(sprint)
    "width: #{sprint.process_in_percents}%;"
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/sprints_helper.rb
module SprintsHelper
  def sprint_state(state)
    case state
    when 1
      t(:opened)
    when 0
      t(:closed)
    when 2
      t(:in_work)
    when 3
      t(:for_closing)
    else
      t(:something_went_wrong)
    end
  end
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/issues/index.html.slim
- if notice
  p#notice
    = notice

p.sprints_title
  = t('issue')

.col-xs-6
  .issues_c.issue_accept
    - @issues.each do |issue|
      - unless issue.sprint_id && @sprint.id
        div[class="one_issue #{issue.status}" draggable="true"]
          p
            => t('issue_#')
            = issue.id
          p
            => t('subject:')
            = link_to issue.subject, @issue_url + issue.id.to_s
          p
            => t('status:')
            = issue.status
          p
            =>  t('assigned_to:')
            - if issue.client
              = issue.client.name
          .row
            .progress
              .progress-bar.progress-bar-striped style=progressbar_percent(issue)
                .stats
                  = issue.hours.to_i
                  |/
                  = issue.estimated_hours.to_i
          = button_to I18n.t(:add_to_sprint), issue_path(issue, sprint_id: @sprint.id), method: :patch

.col-xs-6
  .issues_c.issue_accept
    - if @sprint
      p
        => t('sprint_name:')
        = @sprint.name
      hr
      p
        => t('sprint_hours:')
      .row
        .progress
          .progress-bar.progress-bar-striped style=progressbar_percent(@sprint)
            .stats
              = @sprint.hours_to_sprint.to_i
              |/
              = @sprint.work_hours
      hr
        => t('common_estimeted_time:')
        = @sprint.estimated_hours_to_sprint
      hr
        => t('clients:')
      - @sprint.clients.each do |client|
        = client.name
        br
      hr
        .close_sprint
        = button_to I18n.t(:start_sprint), start_sprint_path(@sprint), method: :patch
        = button_to I18n.t(:show_sprint), sprint_path(@sprint), method: :get
      - @issues.each do |issue|
        - if issue.sprint_id == @sprint.id
          div[class="one_issue #{issue.status}" draggable="true"]
            p
              => t('issue_#')
              = issue.id
            p
              => t('subject:')
              = link_to issue.subject, @issue_url + issue.id.to_s
            p
              => t('status:')
              = issue.status
            p
              =>  t('assigned_to:')
              - if issue.client
                = issue.client.name
            .row
              .progress
                .progress-bar.progress-bar-striped style=progressbar_percent(issue)
                  .stats
                    = issue.hours.to_i
                    |/
                    = issue.estimated_hours.to_i
            .remove
              = link_to I18n.t(:x), issue_path(issue), method: :patch
  .edit_spint
    = link_to t(:edit_sprints), sprints_path

app/views/layouts/application.html.slim
doctype html
html
  head
    title Distributor
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag "//www.google.com/jsapi", "chartkick"
    = csrf_meta_tags
  body
    .header
      .logout
        - if session[:user_id]
          = button_to :Logout, logout_path, method: :delete, class: 'out'
        - else
          = button_to :Login, login_path, class: 'out'
    .container#wrapper
      = yield
    .white_block
    footer.footer

app/views/session/new.html.erb
<div class="container">

	<% if flash[:alert] %>
		<p id="notice1"><%= flash[:alert] %></p>
	<% end %>


	<%= form_tag do %>
	<fieldset>
		<div class="auto_form">
			<div class="face">			
			</div>

			<div class="user_name">
				<%= label_tag :name, 'Name: ' %><br>
				<%= text_field_tag :name, params[:name], class: "pin_input" %>
			</div>

			<div class="user_pass">
				<%= label_tag :password, 'Password: ' %><br>
				<%= password_field_tag :password, params[:password], class: "pin_input" %>
			</div>			
			
			<div class="login_button">
				<%= submit_tag "Login" %>
			</div>
		</div>
	</fieldset>
	<% end %>
</div>

app/views/session/new.html.slim
- if flash[:alert]
  p#notice1
    = flash[:alert]

= form_tag do
  fieldset
    .auto_form
      .user_name
        = label_tag :name, t(:name)
        br
        = text_field_tag :name, params[:name], class: "pin_input"
      .user_pass
        = label_tag :password, t(:password)
        br
        = password_field_tag :password, params[:password], class: "pin_input"
      .login_button
        = button_tag :Login

app/views/sprints/_form.html.erb
<%= form_for(@sprint) do |f| %>
  <% if @sprint.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sprint.errors.count, "error") %> prohibited this sprint from being saved:</h2>

      <ul>
      <% @sprint.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<table class="sprints_list">
  <tr>
    <td>
      <%= f.label :name %>
    </td>    
    <td>
      <%= f.text_field :name, class: "text_field"%>
    </td>
  </tr>
  <tr>
    <td>
      <%= f.label :state %> 
    </td>
    <td>  
      <%= f.check_box :state, {}, "true", "false"%> 
    </td>   
  </tr>
  <tr>
    <td>
      <%= f.label :clients %>
    </td>
    <td>
      <%= f.select :clients, options_from_collection_for_select(@clients, 'id', 'name'), {} ,:multiple => true %>
    </td>
  </tr>
</table> 

  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/sprints/_form.html.slim
= form_for(@sprint) do |f|
  - if @sprint.errors.any?
    #error_explanation
      h2 id="err"
        = pluralize(@sprint.errors.count, "error")
      ul
        -@sprint.errors.full_messages.each do |message|
          li = message

  table class="sprints_list"
    tr
      td = f.label :name
      td = f.text_field :name, class: "text_field"
    tr
      td = f.label :state
      td
        =' f.check_box :state, {}, "1", "0"
        = t('opened')
    tr
      td = f.label :adding_clients
      td = f.select :client_ids, options_from_collection_for_select(@clients, 'id', 'name', @collect_selected), {}, multiple: true
  .actions
    = f.submit

app/views/sprints/edit.html.erb
<p class="sprints_title">Editing Sprint</p>

<%= render 'form' %>

<div class="sprint_link">
	<%= link_to 'Show', @sprint %>
</div>
<div class="sprint_link">
	<%= link_to 'Back', sprints_path %>
</div>

app/views/sprints/edit.html.slim
p.sprints_title = t('editing_sprint')

= render 'form'

.sprint_link
  = link_to t(:show), @sprint
.sprint_link
  = link_to t(:back), sprints_path

app/views/sprints/index.html.erb
<p class="sprints_title">Sprints</p>

<table class="sprints_list">
  <% @sprints.each do |sprint| %>
      <tr>
                 
        <td class="list_description">
          <dl>
            <dt><%= sprint.name %></dt>
          </dl>
        </td>

        <td class="list_actions">
          <%= link_to 'Show', sprint %><br>
          <%= link_to 'Edit', edit_sprint_path(sprint) %><br>
          <%= link_to 'Destroy', sprint, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>

        <td class="list_clients">
          <% sprint.clients.each do |client| %>
            <%= client.name %>
            <br>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>

<div class="sprint_link">
  <%= link_to 'New Sprint', new_sprint_path %>
</div>

app/views/sprints/index.html.slim
- if notice
  p#notice
    = notice

p.sprints_title
  = t('sprints')

table.sprints_list
  tr.hat
    td
      = t('name')
    td
    td
      = t('clients')
    td
      = t('status')
    td
      = t('hours')
    td
      = t('all_issues')
  - @sprints.each do |sprint|
      tr[class="state#{sprint.state}"]
        td.list_description
          dl
            dt = sprint.name
        td.list_actions
          = link_to t(:show), sprint
          - if session[:user_id]
            br
            - if sprint.state == 1
              = link_to t(:edit), edit_sprint_path(sprint)
            br
            = link_to t(:destroy), sprint, method: :delete, data: { confirm: 'Are you sure?' }
        td.list_clients
          - sprint.clients.each do |client|
            = client.name
            br
        td
          = sprint_state(sprint.state)
        td.total_time
          = sprint.work_hours
        td
          - sprint.issues.each do |issue|
            => t('issue_#')
            = issue.id
            br

br

- if session[:user_id]
  - unless @sprints.exists?(state: 1)
    .sprint_link
      = link_to t(:new_sprint), new_sprint_path
  .edit_spint
    = link_to t(:go_to_issues), issues_path

app/views/sprints/new.html.erb
<p class="sprints_title">New Sprint</p>

<%= render 'form' %>

<div class="sprint_link">
	<%= link_to 'Back', sprints_path %>
</div>

app/views/sprints/new.html.slim
p.sprints_title = t('new_sprint')

= render 'form'

.sprint_link
  = link_to t(:back), sprints_path

app/views/sprints/show.html.erb
<p id="notice"><%= notice %></p>


<div class="sprints_list">
<p class="show">
  <strong>Name:</strong>
  <%= @sprint.name %>
</p>

<p class="sprint_show show">
  <strong>State:</strong>
  <%= @sprint.state %>
</p>

<p class="sprint_show show"> 
  <strong>Clients:</strong>
	<% @sprint.clients.each do |client|%>
	<%= client.name %>
	<br>
	<% end %> 
</p>
</div>

<div class="sprint_link">
	<%= link_to 'Edit', edit_sprint_path(@sprint) %>
</div>
<div class="sprint_link">
	<%= link_to 'Back', sprints_path %>
</div>

app/views/sprints/show.html.slim
- if notice
  p#notice
    = notice

.sprints_list
  p.show
    strong' = t('name:')
    = @sprint.name
  p.sprint_show.show
    strong' = t('state:')
    = sprint_state(@sprint.state)
  p.sprint_show.show
    strong' = t('clients:')
    br
    - @sprint.clients.each do |client|
      = client.name
      br
  p.sprint_show.show
    strong' = t('sprint_time:')
  .show_bar
    .row
      .progress
        .progress-bar.progress-bar-striped style=progressbar_percent(@sprint)
          .stats
            = @sprint.hours_to_sprint.to_i
            |/
            = @sprint.work_hours
  p.sprint_show.show
    strong' = t('issues:')
    .issues_c
      - @sprint.issues.each do |issue|
        - if issue
          div[class="one_issue #{issue.status}"]
            p
              => t('issue_#')
              = issue.id
            p
              => t('subject:')
              = link_to issue.subject, @issue_url + issue.id.to_s
            p
              => t('status:')
              = issue.status
            p
              =>  t('assigned_to:')
              - if issue.client
                = issue.client.name
            .row
              .progress
                .progress-bar.progress-bar-striped style=progressbar_percent(issue)
                  .stats
                    = issue.hours.to_i
                    |/
                    = issue.estimated_hours.to_i
  p.sprint_show.show
    - if @sprint.start_time
      = line_chart [{name: "work hours", data: @sprint.graph},
                    {name: "norm", data: ({@sprint.start_time => @sprint.work_hours, @sprint.start_time + 10 => 0})}]
  - if @sprint.state == 2 && session[:user_id]
    .close_me
      = button_to I18n.t(:close_sprint), close_sprint_path(@sprint), method: :patch

.links
  - if session[:user_id]
    - if @sprint.state == 1
      .sprint_link
        = link_to t(:edit), edit_sprint_path(@sprint)
    .sprint_link
      = link_to t(:planing_open_sprint), issues_path
  .sprint_link
    = link_to t(:back), sprints_path

app/views/users/index.html.erb
<h1>Добро пожаловать</h1>

Сейчас <%= Time.now %>
<br>
У нас работают <%= pluralize(@total_clients, "woker") %>